src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->end_at;
    }

    public function setEndAt(\DateTimeInterface $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
//            ->add('name')
//            ->add('description')
//            ->add('start_at')
//            ->add('end_at')
//        ;






        ->add('name', TextType::class, [
        // 'label' => ['title',
        //             'class'=>'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6'
        // ],
        'attr' => [
            'autocomplete' => 'name',
            'class' => 'block py-2.5 px-0 my-5 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer',
            'placeholder' => 'eg.The building name'
        ],
    ])



        ->add('description', TextareaType::class, [
            // 'label' => ['title',
            //             'class'=>'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6'
            // ],
            'attr' => [
                'autocomplete' => 'description',
                'class' => 'block py-2.5 my-5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer',
                'placeholder' => 'eg.The description'
            ],
        ])


        ->add('start_at', DateType::class, [

            'widget' => 'single_text',
            // this is actually the default format for single_text
            'format' => 'yyyy-MM-dd',


        ])

        ->add('end_at', DateType::class, [

            'widget' => 'single_text',
            // this is actually the default format for single_text
            'format' => 'yyyy-MM-dd',

        ])
//
//
//            ->add('start_at', DateType::class, [
//                'widget' => 'single_text',
//                'attr' => ['class' => 'datepicker'],
//                'html5' => false,
//                'mapped' => true,
//                'format' => 'yyyy-MM-dd',
//            ])

//            ->add('end_at', DateType::class, [
//                'widget' => 'single_text',
//                'attr' => ['class' => 'datepicker'],
//                'html5' => false,
//                'mapped' => true,
//                'format' => 'yyyy-MM-dd',
//            ])




    ;

    }






    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/task')]
class TaskController extends AbstractController
{
    #[Route('/', name: 'app_task_index', methods: ['GET'])]
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('task/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_task_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TaskRepository $taskRepository): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taskRepository->save($task, true);

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('task/new.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_task_show', methods: ['GET'])]
    public function show(Task $task): Response
    {
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, TaskRepository $taskRepository): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taskRepository->save($task, true);

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_task_delete', methods: ['POST'])]
    public function delete(Request $request, Task $task, TaskRepository $taskRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $taskRepository->remove($task, true);
        }

        return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="uppercase my-20 bg-blue-500 text-gray-100 text-lg w-1/5 mt-10 font-extrabold py-4 px-8 rounded-3xl">
        {{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/task/edit.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_task_index') }}">back to list</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

templates/task/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}



    <main class="flex-1 flex bg-gray-50 mx-auto w-full">
        <section class="bg-gray-50 dark:bg-gray-50  w-full">
            <div class="mx-auto w-4/5 my-8">
                <a
                        href="{{ path('app_task_new') }}"
                        class="uppercase border border-gray-500 text-lg py-4 px-6 rounded transition transition-all bg-gray-800 text-white hover:bg-white hover:text-gray-800">
                    Create New
                </a>
            </div>
            <div class="relative overflow-x-auto shadow-md sm:rounded-lg ">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                           Task Id
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Task Name
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Description
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Start At
                        </th>
                        <th scope="col" class="px-6 py-3">
                            End At
                        </th>
                        <th scope="col" class="px-6 py-3">

                        </th>

                    </tr>
                    </thead>
                    {% for task in tasks %}
                        <tbody>
                        <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{ task.id }}
                            </th>
                            <td class="px-6 py-4">
                                {{ task.name }}
                            </td>
                            <td class="px-6 py-4">
                                {{ task.description }}
                            </td>
                            <td class="px-6 py-4">
                                {{ task.startAt ? task.startAt|date('Y-m-d H:i:s') : '' }}
                            </td>
                            <td class="px-6 py-4">
                                {{ task.endAt ? task.endAt|date('Y-m-d H:i:s') : '' }}
                            </td>
                            <td class="px-6 py-4">
                                <a
                                        href="{{ path('app_task_show', {'id': task.id}) }}"
                                        class="bg-green-500 font-bold py-2 px-4 rounded transition-all hover:bg-green-300">
                                    show
                                </a>
                                <a
                                        href="{{ path('app_task_edit', {'id': task.id}) }}"
                                        class="bg-red-500 font-bold py-2 px-4 rounded transition-all hover:bg-red-300">
                                    edit
                                </a>
                            </td>

                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>


                        </tbody>
                    {% endfor %}
                </table>

            </div>
        </section>
    </main>

{% endblock %}

templates/task/new.html.twig
{% extends 'base2.html.twig' %}

{% block title %}New Task{% endblock %}

{% block body %}
{#<div class="w-4/5 m-auto text-center">#}
{#    <div class="py-6 border-b border-gray-200">#}
{#        <h1 class="text-6xl pt-6 pb-5">#}
{#            Create Tasks#}
{#        </h1>#}

{#    {{ include('task/_form.html.twig') }}#}
{#<div class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg w-1/5 mt-10 font-extrabold py-4 px-8 rounded-3xl">#}
{#    <a href="{{ path('app_task_index') }}">back to list</a>#}
{#</div>#}
{#    </div>#}
{#</div>#}



    <div class="w-4/5 m-auto text-center">
        <div class="py-6 border-b border-gray-200">
            <h1 class="text-6xl pt-6 pb-5">
                Create Task Details
            </h1>
            <div class="m-auto w-4/5 my-8">
                <a
                        href="{{ path('app_task_index') }}"
                        class="uppercase border border-gray-500 text-lg py-4 px-6 rounded transition transition-all bg-gray-800 text-white hover:bg-white hover:text-gray-800">
                    back to list
                </a>
            </div>

            {{ form_start(form) }}

            {{ form_widget(form)}}

            <button
                    type="submit"
                    class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg w-1/5 mt-10 font-extrabold py-4 px-8 rounded-3xl">
                create
            </button>


            {{ form_start(form) }}
        </div>
    </div>
{% endblock %}

templates/task/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ task.description }}</td>
            </tr>
            <tr>
                <th>Start_at</th>
                <td>{{ task.startAt ? task.startAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_at</th>
                <td>{{ task.endAt ? task.endAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_task_index') }}">back to list</a>

    <a href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}