src/Entity/Building.php
<?php

namespace App\Entity;

use App\Repository\BuildingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BuildingRepository::class)]
class Building
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $code = null;

    #[ORM\Column(length: 255)]
    private ?string $ImagePath = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'building', targetEntity: Officess::class, orphanRemoval: true)]
    private Collection $offices;

    #[ORM\ManyToOne(inversedBy: 'buildings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Infrastructure::class, mappedBy: 'buildind')]
    private Collection $infrastructures;

    #[ORM\OneToOne(mappedBy: 'buildings', cascade: ['persist', 'remove'])]
    private ?Classroom $classroom = null;

    #[ORM\OneToOne(mappedBy: 'building', cascade: ['persist', 'remove'])]
    private ?Messages $messages = null;

    public function __construct()
    {
        $this->offices = new ArrayCollection();
        $this->infrastructures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(int $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->ImagePath;
    }

    public function setImagePath(string $ImagePath): self
    {
        $this->ImagePath = $ImagePath;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Officess>
     */
    public function getOffices(): Collection
    {
        return $this->offices;
    }

    public function addOffice(Officess $office): self
    {
        if (!$this->offices->contains($office)) {
            $this->offices->add($office);
            $office->setBuilding($this);
        }

        return $this;
    }

    public function removeOffice(Officess $office): self
    {
        if ($this->offices->removeElement($office)) {
            // set the owning side to null (unless already changed)
            if ($office->getBuilding() === $this) {
                $office->setBuilding(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->name;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Infrastructure>
     */
    public function getInfrastructures(): Collection
    {
        return $this->infrastructures;
    }

    public function addInfrastructure(Infrastructure $infrastructure): self
    {
        if (!$this->infrastructures->contains($infrastructure)) {
            $this->infrastructures->add($infrastructure);
            $infrastructure->addBuildind($this);
        }

        return $this;
    }

    public function removeInfrastructure(Infrastructure $infrastructure): self
    {
        if ($this->infrastructures->removeElement($infrastructure)) {
            $infrastructure->removeBuildind($this);
        }

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->classroom;
    }

    public function setClassroom(Classroom $classroom): self
    {
        // set the owning side of the relation if necessary
        if ($classroom->getBuildings() !== $this) {
            $classroom->setBuildings($this);
        }

        $this->classroom = $classroom;

        return $this;
    }

    public function getMessages(): ?Messages
    {
        return $this->messages;
    }

    public function setMessages(Messages $messages): self
    {
        // set the owning side of the relation if necessary
        if ($messages->getBuilding() !== $this) {
            $messages->setBuilding($this);
        }

        $this->messages = $messages;

        return $this;
    }
}

src/Controller/BuildingController.php
<?php

namespace App\Controller;

use App\Entity\Building;
use App\Form\BuildingFormType;
use App\Repository\BuildingRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BuildingController extends AbstractController
{
  private $buildingRepository;
    private $em;

    public function __construct(BuildingRepository $buildingRepository , EntityManagerInterface $em){
        $this->buildingRepository = $buildingRepository;
        $this->em =$em;
    }
  
    //#[Route('/frontpage', methods:['GET'], name: 'app_front_page')]
    #[Route('/building', methods:['GET'], name: 'buildings')]
    public function index(): Response
    {
        $building = $this->buildingRepository->findAll();

        return $this->render('building/index.html.twig', [
            'buildings' => $building,
        ]);
    }


    #[Route('/building/{id}',methods:['GET'],name:'show_building')]
    public function show($id):Response
    {
        $building =$this->buildingRepository->find($id);

        return $this->render('building/show.html.twig',[
            'building'=>$building
        ]);
    }
 
    #[Route('/CreateBuilding', name:'create_building')]
    public function create(Request $request): Response {
 
      $building = new Building();
      $form =$this->createForm(BuildingFormType::class, $building);

      $form->handleRequest($request);
      
      if($form->isSubmitted() && $form->isValid()) {

        $newBuilding = $form->getData();

        $ImagePath= $form->get('ImagePath')->getData();
       
        if($ImagePath){
          $newFileName= uniqid() . '.'. $ImagePath->guessExtension();   
         
          try{
               $ImagePath->move(
                $this->getParameter('kernel.project_dir') . '/public/uploads',
                $newFileName
               );
          }catch(FileException $e){
           return new Response($e->getMessage());
          }

          $newBuilding->setImagePath('/uploads/' . $newFileName);
        }
        $this->em->persist($newBuilding);
        $this->em->flush();
        return $this->redirectToRoute('building');
      }
      
      return $this->render('building/create.html.twig',[
        'buildingForm'=>$form->createView()
      ]);
    }

    #[Route('/building/edit/{id}',name:'edit_building')]
       public function edit($id, Request $request):Response{
        $building= $this->buildingRepository->find($id);
        $form =$this->createForm(BuildingFormType::class,$building);

        $form->handleRequest($request);
           $ImagePath = $form->getImagePath('ImagePath')->getData();

           if ($form->isSubmitted() && $form->isValid()) {
               if($ImagePath){
                   if ($ImagePath->get()!==null){
                       if (file_exists(
                           $this->getParameter('kernel.project_dir').$building->getImagePath()
                       )) {
                           $this->GetParameter('kernel.project_dir').$building->getImagePath();

                           $newFileName = uniqid() . '.' . $ImagePath->guessExtension();

                           try{
                               $ImagePath->move(
                                   $this->getParameter('kernel.project_dir') . '/public/uploads',
                                   $newFileName
                               );
                           }catch(FileException $e){
                               return new Response($e->getMessage());
                           }
                           $building->setImagePath('/uploads' . $newFileName);
                           $this->em->flush();

                           return $this->redirectToRoute('buildings');


                       }

                   }
               }else{
                   $building->setName($form->get('name')->getData());
                   $building->setDescription($form->get('description')->getData());
                   $building->setCode($form->get('code')->getData());


                   $this->em->flush();
                   return $this->redirectToRoute('buildings');
               }
           }
           return $this->render('building/edit.html.twig',[
               'buildings'=> $building,
               'buildingForm'=>$form->createView()
           ]);
       }

}

templates/building/create.html.twig
{#{% extends "./base2.html.twig" %}#}

{#        {% block body %}#}


{#            <main class="flex-1 flex bg-gray-50 mx-auto mt-4">#}
{#                <section class="bg-gray-50 dark:bg-gray-50 w-full h-50">#}
{#                    <div class="flex flex-col items-center justify-center px-6 py-8 md:h-screen lg:py-0">#}
{#                        <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">#}
{#                            #}{# <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">#}
{#                            Flowbite     #}
{#                        </a>#}
{#                        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">#}
{#                            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">#}
{#                                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">#}
{#                                    Create Building Details#}
{#                                </h1>#}
{#                                {{ form_start(buildingForm) }}#}
{#                                <div class="relative z-0 w-full mb-6 group">#}
{#                                    {{ form_widget(buildingForm, {'attr': {'class': 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer'}}) }}#}
{#                                </div>#}
{#                                #}{# <div class="relative z-0 w-full mb-6 group">#}
{#                                            {{ form_row(detailForm.title) }}#}
{#                                             {{ form_row(detailForm.decription) }}#}
{#                                                {{ form_row(detailForm.imagePath) }} #}
{#                                <button#}
{#                                        type="submit"#}
{#                                        class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg font-extrabold py-4 px-8 rounded-3xl">#}
{#                                    Submit Post#}
{#                                </button>#}

{#                                {{ form_end(buildingForm) }}#}

{#                            </div>#}
{#                        </div>#}
{#                    </div>#}

{#                </section>#}
{#            </main>#}
{#        {% endblock %}#}









{% extends 'base2.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}
    <div class="w-4/5 m-auto text-center">
        <div class="py-6 border-b border-gray-200">
            <h1 class="text-6xl pt-6 pb-5">
                Create Building Details
            </h1>

            {{ form_start(buildingForm) }}

                   {{ form_widget(buildingForm)}}

            <button
                    type="submit"
                    class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg w-1/5 mt-10 font-extrabold py-4 px-8 rounded-3xl">
                submit
            </button>


            {{ form_start(buildingForm) }}
        </div>
    </div>
{% endblock %}

















































{#{% extends 'base2.html.twig' %}#}

{#{% block title %}front detail{% endblock %}#}

{#{% block body %}#}
{#    #}{# <div class="w-4/5 m-auto text-center">#}
{#        <div class="py-12 border-b border-gray-200">#}
{#            <h1 class="text-6xl pt-12 pb-8">#}
{#                Register#}
{#            </h1>#}

{#            {{ form_start(registrationForm) }}#}
{#                {{ form_row(registrationForm.email) }}#}
{#                {{ form_row(registrationForm.plainPassword) }}#}
{#            #}
{#            {{ form_row(registrationForm.agreeTerms) }}#}
{#            #}
{#            <button #}
{#                type="submit" #}
{#                class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg w-1/5 mt-10 font-extrabold py-4 px-8 rounded-3xl">#}
{#                Register#}
{#            </button>#}
{#            #}
{#            {{ form_end(registrationForm) }}#}

{#        </div>#}
{#    </div> #}
{#<div class="flex flex-1 overflow-hidden">#}
{#    <div class="w-64 p-6 bg-gray-100 overflow-y-auto">#}
{#        <nav>#}
{#            <h2 class="text-xs font-semibold text-gray-600 uppercase tracking-wider">#}
{#                Mailboxes#}
{#            </h2>#}

{#            <div class="mt-3">#}
{#                <a href="#" class="mt-2 -mx-3 px-3 py-2 flex items-center justify-between text-sm font-medium bg-gray-200 rounded-lg">#}
{#            <span class="inline-flex align-baseline">#}
{#              <span class="leading-normal">#}
{#              <i class="fas fa-inbox h-5 w-5 fill-current text-gray-700 "></i>#}
{#              </span>#}
{#              <span class="ml-2 text-gray-900">Inbox</span>#}
{#            </span>#}
{#                    <span class="w-10 text-center py-1 text-xs font-semibold rounded-full text-gray-700 bg-gray-300">#}
{#              6#}
{#            </span>#}
{#                </a>#}
{#                <a href="#" class="mt-2 -mx-3 px-3 py-2 flex items-center justify-between text-sm font-medium hover:bg-gray-200 rounded-lg">#}
{#            <span class="inline-flex align-baseline">#}
{#              <span class="leading-normal">#}
{#              <i class="far fa-flag h-5 w-5 fill-current text-gray-500 "></i>#}
{#              </span>#}
{#              <span class="ml-2 text-gray-700">Flagged</span>#}
{#            </span>#}
{#                </a>#}
{#                <a href="#" class="mt-2 -mx-3 px-3 py-2 flex items-center justify-between text-sm font-medium hover:bg-gray-200 rounded-lg">#}
{#            <span class="inline-flex align-baseline">#}
{#              <span class="leading-normal">#}
{#              <i class="far fa-edit h-5 w-5 fill-current text-gray-500 "></i>#}
{#              </span>#}
{#              <span class="ml-2 text-gray-700">Drafts</span>#}
{#            </span>#}
{#                    <span class="w-10 text-center py-1 text-xs font-semibold rounded-full text-gray-700 bg-gray-300">#}
{#              2#}
{#            </span>#}
{#                </a>#}
{#                <a href="#" class="mt-2 -mx-3 px-3 py-2 flex items-center justify-between text-sm font-medium hover:bg-gray-200 rounded-lg">#}
{#            <span class="inline-flex align-baseline">#}
{#              <span class="leading-normal">#}
{#              <i class="far fa-user-circle h-5 w-5 fill-current text-gray-500 "></i>#}
{#              </span>#}
{#              <span class="ml-2 text-gray-700">Assigned</span>#}
{#            </span>#}
{#                    <span class="w-10 text-center py-1 text-xs font-semibold rounded-full text-gray-700 bg-gray-300">#}
{#              1#}
{#            </span>#}
{#                </a>#}
{#                <a href="#" class="mt-2 -mx-3 px-3 py-2 flex items-center justify-between text-sm font-medium hover:bg-gray-200 rounded-lg">#}
{#            <span class="inline-flex align-baseline">#}
{#              <span class="leading-normal">#}
{#              <i class="far fa-check-circle h-5 w-5 fill-current text-gray-500 "></i>#}
{#              </span>#}
{#              <span class="ml-2 text-gray-700">Closed</span>#}
{#            </span>#}
{#                </a>#}
{#                <a href="#" class="mt-2 -mx-3 px-3 py-2 flex items-center justify-between text-sm font-medium hover:bg-gray-200 rounded-lg">#}
{#            <span class="inline-flex align-baseline">#}
{#              <span class="leading-normal">#}
{#              <i class="fas fa-trash h-5 w-5 fill-current text-gray-500 "></i>#}
{#              </span>#}
{#              <span class="ml-2 text-gray-700">Junk</span>#}
{#            </span>#}
{#                </a>#}

{#            </div>#}

{#            <h2 class="mt-8 text-xs font-semibold text-gray-600 uppercase tracking-wider">#}
{#                Folders#}
{#            </h2>#}
{#            <div class="mt-4">#}
{#                <a href="#" class=" block text-sm font-medium text-gray-700">Refunds</a>#}
{#                <a href="#" class="mt-4 block text-sm font-medium text-gray-700">Discounts</a>#}
{#                <a href="#" class="mt-4 block text-sm font-medium text-gray-700">Bugs</a>#}
{#            </div>#}
{#        </nav>#}
{#    </div>#}

{#    <main class="flex-1 flex bg-gray-200">#}
{#    <section class="bg-gray-50 dark:bg-gray-900  w-full">#}
{#  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">#}
{#      <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">#}
{#          #}{# <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">#}
{#          Flowbite     #}
{#      </a>#}
{#      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">#}
{#          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">#}
{#              <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">#}
{#                  Create Building Details#}
{#              </h1>#}
{# {{ form_start(buildingForm) }}#}
{#<div class="relative z-0 w-full mb-6 group">#}
{#        {{ form_widget(buildingForm, {'attr': {'class': 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer'}}) }}#}
{#     </div>#}
{# <div class="relative z-0 w-full mb-6 group">#}
{#            {{ form_row(detailForm.title) }}#}
{#             {{ form_row(detailForm.decription) }}#}
{#                {{ form_row(detailForm.imagePath) }} #}
{#        <button    #}
{#            type="submit"#}
{#            class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg font-extrabold py-4 px-8 rounded-3xl">#}
{#            Submit Post#}
{#        </button>#}

{#    {{ form_end(buildingForm) }}#}

{#          </div>#}
{#      </div>#}
{#  </div>#}
{#</section>#}
{#    </main>#}
{#    #}
{#    #}
{#    #}
{#    #}
{#    #}
{#    #}
{#</div>#}
{#{% endblock %}#}



{#/////////////#}

templates/building/edit.html.twig
{% extends "./base2.html.twig" %}

        {% block body %}


            <main class="flex-1 flex bg-gray-50">
                <section class="bg-gray-50 dark:bg-gray-50  w-full">
                    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                        <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
                            {# <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">
                            Flowbite     #}
                        </a>
                        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                                    Edit Building Details
                                </h1>
                                {{ form_start(buildingForm) }}
                                <div class="relative z-0 w-full mb-6 group">
                                    {{ form_widget(buildingForm, {'attr': {'class': 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer'}}) }}



{#                                    {{ form_row(buildingForm.name) }}#}
{#                                    {{ form_row(buildingForm.description) }}#}
{#                                    {{ form_row(buildingForm.code) }}#}
{#                                    {{ form_row(buildingForm.ImagePath) }} #}
                                </div>
                                {# <div class="relative z-0 w-full mb-6 group">
                                            {{ form_row(detailForm.title) }}
                                             {{ form_row(detailForm.decription) }}
                                                {{ form_row(detailForm.imagePath) }} #}
                                <button
                                        type="submit"
                                        class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg font-extrabold py-4 px-8 rounded-3xl">
                                    Submit Post
                                </button>

                                {{ form_end(buildingForm) }}

                            </div>
                        </div>
                    </div>

                </section>
            </main>
        {% endblock %}